# Generated by Django 6.1 on 2026-08-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='nome do jogador')),
                ('score', models.PositiveIntegerField(verbose_name='pontuação')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='nível alcançado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
            ],
            options={
                'verbose_name': 'recorde',
                'verbose_name_plural': 'recordes',
                'ordering': ['-score', 'created_at'],
            },
        ),
    ]
